import "./globals.css";

export const metadata = {
  title: "Naruto memory game",
  description: "Generated by create next app (Mobina Yousefian)",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      {children}
      </body>
    </html>
  );
}
